import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [numBusinessMedia, setNumBusinessMedia] = useState(0);
  const [numComputingIT, setNumComputingIT] = useState(0);
  const [numStudy, setNumStudy] = useState(0);

  const [educationBusinessMedia, setEducationBusinessMedia] = useState([])

  const getSchoolData = async () => {
    const result = await axios.get("https://mszucseducation.github.io/data/education.json");
    console.log(result);
    setNumBusinessMedia(result.data.bcit[0].businessMedia.length);
    setNumComputingIT(result.data.bcit[0].computingIT.length)
    setEducationBusinessMedia([
      ...result.data.bcit[0].businessMedia
    ])
    setNumStudy(result.data.bcit[0].businessMedia.length)
  }

  const getCountAndInformation = () => {
    console.log("business media", numBusinessMedia)
    console.log("Computing & IT", numComputingIT)
    console.log(educationBusinessMedia);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <button onClick={() => getSchoolData()}>Get all education</button>
          <button onClick={() => getCountAndInformation()}>Get Count and Info</button>
        </div>
        {
          numStudy > 0 && educationBusinessMedia.map(
            (ed, index) => (
              <div key={index}>
                <b>{ed.subDepartment}</b>
                <ul>
                  {
                    numBusinessMedia > 0 && educationBusinessMedia[index].study.map(
                        (s, indexTwo) => (
                          <li key={indexTwo} id={"id"+indexTwo}>{s}</li>
                        )
                    )
                  }
                </ul>
              </div>
            )
          )
        }
      </main>
    </>
  )
}
